<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>LibSixel.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>LibSixel.PowerShell</AssemblyName>
    <RootNamespace>LibSixel.PowerShell</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="2.88.9" />
    <PackageReference Include="Svg.Skia" Version="3.4.1" />
    <PackageReference Include="System.Management.Automation" Version="7.4.15" PrivateAssets="all" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibSixel\LibSixel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="LibSixel.PowerShell.psd1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopySkiaNativeLibraries" AfterTargets="Build">
    <ItemGroup>
      <SkiaNativeLibrary Include="$(OutDir)runtimes/*/native/*SkiaSharp*" />
    </ItemGroup>
    <Copy SourceFiles="@(SkiaNativeLibrary)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
